### ISSUE TITLE
Assigns to global outside of an event

### ISSUE THREAD

**Issue by Nexela** [Brickcaster/factoriorpg#4]
on_init and on_configuration changed are where global designations should go.

doing it outside of those events leads to stuff not working correctly if this is put into an existing world, or the author decides to add/change the global.vars at a later date.

**Comment by Brickcaster** [comment]
Could you reference a specific place?  Globals can be defined in the global scope (not inside of a function), but they're overwritten on load if they already exist in the save.  As this is designed to be a scenario, adding these into an existing game would not trigger on_init or on_configuration changed so running it in the global scope is the only way some vars are going to get defined.

What you're referencing is likely intended behavior.

**Comment by Nexela** [comment]
Hmmm I didn't think about the on configuration changed thing.

Running it in the global namespace will guarantee it won't work if added mid scenario.
While adding it mid scenario won't be a common thing one way to get around this is to make a /command that runs `Event.dispatch({name = Event.core_events.on_configuration_changed})` Though this won't be the greatest way either.....

Option xxx34x32 is the soon<tm> configuration_changed module for stdlib

I will come up with a better solution soon!

**Comment by Brickcaster** [comment]
I've tested before and everything in the global namespace gets executed on game load, and then the save data is applied to the global table.  This is how changed functions get updated, but it also applies to global data.  Except for the aforementioned lack of persistence.    The game also lacks the LuaGameScript struct at this stage, but it's not a big deal.

**Comment by Brickcaster** [comment]
Scenario has global writing detection built in to avoid these kinds of issues and it has been successfully used for some item.  This issue seems to be resolved.
